# Use a base image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Rebuild bcrypt to ensure it's compatible with the Docker environment
RUN npm rebuild bcrypt --build-from-source

# Expose the port your application runs on
EXPOSE 4000

# Command to run the application
CMD ["npm", "start"]
